services:
  server:
    image: ${{ secrets.REGISTRY_URL }}/pepegov/chat.server:latest
    container_name: pepegov.chat.server
    restart: always
    ports:
      - "11000:11000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerUrl__Authority=identity.server.ru
      - ConnectionStrings__DefaultConnection="Server=postgres;Port=5432;User Id=postgres;Password=qweQWE123;Database=Pepegov.Chat"
      - RabbitMQ__Url=localhost
      - RabbitMQ__Host=/
      - RabbitMQ__User=rmuser
      - RabbitMQ__Password=rmpassword
  angular-client:
      image: ${{ secrets.REGISTRY_URL }}/pepegov/chat.client:latest
      container_name: pepegov.chat.client
      restart: always
      ports:
        - "11001:80"