name: 'build and deploy for server'
on:
    push:
        branches: [ master ]
jobs:
    build-server:
        name: 'Build & Publish server'
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v2
            -   name: "Set up QEMU"
                uses: docker/setup-qemu-action@v3
            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.REGISTRY_URL }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_TOKEN }}

            -   name: "Build"
                uses: docker/build-push-action@v5
                with:
                    context: ./src/Pepegov.Chat.Server
                    file: ./src/Pepegov.Chat.Server/PepegovChat/Pepegov.Chat.Server.PL/Dockerfile
                    push: true
                    tags: |
                        ${{ secrets.REGISTRY_URL }}/pepegov/chat.server:latest
                    secrets: |
                        "ASPNETCORE_ENVIRONMENT=Release"
                    build-args: |
                        build_mode=Release
    build-angular-client:
        name: 'Build & Publish angular client'
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v2
            -   name: "Set up QEMU"
                uses: docker/setup-qemu-action@v3
            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.REGISTRY_URL }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_TOKEN }}

            -   name: "Build"
                uses: docker/build-push-action@v5
                with:
                    context: ./src/Pepegov.Chat.Client
                    file: ./src/Pepegov.Chat.Client/Dockerfile
                    push: true
                    tags: |
                        ${{ secrets.REGISTRY_URL }}/pepegov/chat.client:latest
    deploy-server:
        name: 'Deploy server'
        runs-on: ubuntu-latest
        needs: [ build-server, build-angular-client ]
        steps:
            -   name: "Run deploy on server"
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    port: ${{ secrets.SERVER_PORT }}
                    passphrase : ${{ secrets.PASSPHRASE }}
                    script: |
                        cat ~/.docker_password.txt | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
                        cd ${{ secrets.DEPLOY_DIR }}/server
                        docker compose down
                        docker rmi -f ${{ secrets.REGISTRY_URL }}/pepegov/chat.server:latest || true 
                        docker compose pull
                        docker compose up -d